### ISSUE TITLE
Mettre à jour (ajouter/supprimer/modifier) les contacts

### ISSUE THREAD

**Issue by JoeyQuint** [Joey79100/Judo-Gestion_des_adherents#12]
- [x] Ajout des nouveaux contacts
- [x] Modification des contacts mis à jour
- [x] Suppression des contacts supprimés dans le formulaire

**Comment by Joey79100** [comment]
Non résolu, simplement listé dans #17

**Comment by JoeyQuint** [comment]
C'est le Javascript qui historise les actions effectuées dans le formulaire et qui permet donc de retrouver facilement quoi enlever/modifier/ajouter

**Comment by JoeyQuint** [comment]
9158a23 fait fonctionner une partie des choses : le javascript s'occupe de lister les IDs des contacts qui ont été ajoutés, ainsi que les contacts de la base qui ont été supprimés.

Il reste encore à faire la modification, deux solutions pour ça :
1. Même méthode : lister les contacts ayant été modifiés en javascript et passer l'info au PHP juste avant l'envoi du formulaire. La détection pourrait être faite avec du jquery : il faudrait ajouter une classe "modif_quelque_chose" à tous les champs d'un contact et ainsi détecter une modification dans le champ en question grâce à un évènement jquery (ça doit sûrement être possible).

2. Directement depuis le PHP, en mettant simplement à jour tous les contacts restant (après avoir ajouté/supprimés les contacts qui en avaient besoin) : ceux qui ne font ni partie de la liste des contacts ajoutés, ni de celle des contacts supprimés. De toutes façons, mettre à jour un contact qui n'a pas été modifié ne changera rien à ses informations au final.

**Comment by JoeyQuint** [comment]
La solution 1 (JS) a été utilisée : événement onChange sur les champs à guetter qui appelle contactModifie().
