### ISSUE TITLE
Update : clés composées

### ISSUE THREAD

**Issue by JoeyQuint** [Joey79100/Judo-Gestion_des_adherents#20]
model::update est un peu poussiéreux, et ne gère pas les clés composées. Ça va vite devenir un problème quand il va falloir mettre à jour le cours suivi par les adhérents (#17).

**Comment by Joey79100** [comment]
Concerne les tables :
- PASSER (passage des ceintures)
- SUIVRE (inscriptions aux cours)

Nécessaire pour la modification des adhérents (#17)

**Comment by JoeyQuint** [comment]
Fait avec 0df0075e3bafc4059f4d7f5d8e93ffbe7082e860
